### ISSUE TITLE
Suggestion: sysupgrade should terminate gracefully on full partitions.

### ISSUE THREAD

**Issue by ljliman** [jmmv/sysupgrade#5]
Sysupgrade is a fantastic tool, so thank you very much!

However ... ;-)

While using sysupgrade-1.5nb3 to upgrade from NetBSD 7.1.2 to 8.0, my /usr partition went through the roof. Fair enough. It was indeed too small.

The issue is that sysupgrade didn't notice. It just kept trying to pump new files onto the full partition.

I suggest adding more sensitivity to sysupgrade so that it detects a full partition, and aborts gracefully - possibly leavning a status file behind somewhere so it can continue from where it left off when a sysadmin has addressed the issue with the full partition.

Best reagards,
/Lars-Johan Liman

**Comment by ljliman** [comment]
Well, I don't know which exact process is being used to unpack the new files inside sysupgrade, but I'm not surprised to hear it's `tar` ... 😉

I got multiple instances of "file system full" as sysupgrade was extracting files, and the machine was in single-user mode, so pretty much nothing else should have been fiddling with the file system at the time. Unfortunately the logs "slipped out of hand" before I had a chance to properly collect them.

It takes a bit of an effort to recreate the problem, as I was upgrading from 7.1.2. to 8.0. When that happens there are lots of old 7.1.2-files that are redundant in 8.0 but remain in place (using space) until all new files are unpacked, and _then_ they are removed in a second pass.

Now the machine is at 8.0, and unpacking 8.0 on top of 8.0 yields no "extra leftovers", so the process doesn't use any extra space. Unpacking is a 1-to-1 mapping. I would have to reinstall 7.1.2 on a new VM, fill up the /usr partition and then try to upgrade again. Which would take a while, and I don't have unlimited resources for new VMs ... 🙁 I had hoped that it would be kind of a "Ah! Bummer! I forgot to pick up the exit status!" bug, but maybe you _do_ pick that up, in which case I need to investigate further in order to provide you with a more decent problem report to work from.

**Comment by jmmv** [comment]
Yeah, from a quick code inspection, this just seems to be a case of not checking the error code of `tar` (or, actually, `progress`)...

**Comment by ljliman** [comment]
Ack. Thanks for looking at it. This is no show stopper, and in no way urgent, just a suggestion for improving the integrity of the code. Again: the program is immense help as it is, so thank you!
